
// FIX: Removed v9 firestore imports to use v8 compatible syntax.
// import { collection, writeBatch, getDocs, doc } from 'firebase/firestore';
import { db } from './firebase';
import { Product, ProductVariant } from './types';

// Data from user prompt, merged and formatted.
// Price is set to 0.00 as a default ("Consulte").
const SEED_PRODUCTS: Omit<Product, 'id'>[] = [
    { name: "iPhone XR 64GB", image: "https://ganhocerto99.com/get-imagem.php?id=49", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=49" }], details: "seminovo|64GB|Bateria boa", category: "seminovos", price: 999.99 },
    { name: "iPhone XR 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=50", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=50" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 1199.99 },
    { name: "iPhone 11 64GB", image: "https://ganhocerto99.com/get-imagem.php?id=8", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=8" }], details: "seminovo|64GB|Bateria boa", category: "seminovos", price: 1399.99 },
    { name: "iPhone 11 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=9", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=9" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 1599.99 },
    { name: "iPhone 11 Pro 64GB", image: "https://ganhocerto99.com/get-imagem.php?id=10", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=10" }], details: "seminovo|64GB|Bateria boa", category: "seminovos", price: 1799.99 },
    { name: "iPhone 11 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=11", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=11" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 1999.99 },
    { name: "iPhone 11 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=12", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=12" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2149.99 },
    { name: "iPhone 12 64GB (Seminovo)", image: "https://ganhocerto99.com/get-imagem.php?id=13", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=13" }], details: "seminovo|64GB|Bateria boa", category: "seminovos", price: 1649.99 },
    { name: "iPhone 12 128GB (Seminovo)", image: "https://ganhocerto99.com/get-imagem.php?id=14", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=14" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 1899.99 },
    { name: "iPhone 12 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=16", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=16" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 1949.99 },
    { name: "iPhone 12 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=17", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=17" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2249.99 },
    { name: "iPhone 12 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=18", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=18" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2349.99 },
    { name: "iPhone 12 Pro 512GB", image: "https://ganhocerto99.com/get-imagem.php?id=19", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=19" }], details: "seminovo|512GB|Bateria boa", category: "seminovos", price: 2449.99 },
    { name: "iPhone 12 Pro Max 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=20", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=20" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2699.99 },
    { name: "iPhone 12 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=21", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=21" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2899.99 },
    { name: "iPhone 13 128GB (Seminovo)", image: "https://ganhocerto99.com/get-imagem.php?id=22", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=22" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2299.99 },
    { name: "iPhone 13 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=24", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=24" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2449.99 },
    { name: "iPhone 13 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=25", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=25" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2899.99 },
    { name: "iPhone 13 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=26", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=26" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 3099.99 },
    { name: "iPhone 13 Pro Max 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=27", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=27" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 3449.99 },
    { name: "iPhone 13 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=28", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=28" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 3649.99 },
    { name: "iPhone 13 Pro Max 512GB", image: "https://ganhocerto99.com/get-imagem.php?id=29", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=29" }], details: "seminovo|512GB|Bateria boa", category: "seminovos", price: 3849.99 },
    { name: "iPhone 14 128GB (Seminovo)", image: "https://ganhocerto99.com/get-imagem.php?id=30", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=30" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2699.99 },
    { name: "iPhone 14 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=32", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=32" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2899.99 },
    { name: "iPhone 14 Plus 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=33", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=33" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 2799.99 },
    { name: "iPhone 14 Plus 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=34", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=34" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 2999.99 },
    { name: "iPhone 14 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=35", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=35" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 3499.99 },
    { name: "iPhone 14 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=36", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=36" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 3699.99 },
    { name: "iPhone 14 Pro Max 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=37", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=37" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 4199.99 },
    { name: "iPhone 14 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=38", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=38" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 4349.99 },
    { name: "iPhone 15 128GB (Seminovo)", image: "https://ganhocerto99.com/get-imagem.php?id=39", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=39" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 3499.99 },
    { name: "iPhone 15 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=41", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=41" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 4399.99 },
    { name: "iPhone 15 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=42", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=42" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 4649.99 },
    { name: "iPhone 15 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=43", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=43" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 5149.99 },
    { name: "iPhone 15 Pro Max 512GB", image: "https://ganhocerto99.com/get-imagem.php?id=44", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=44" }], details: "seminovo|512GB|Bateria boa", category: "seminovos", price: 5599.99 },
    { name: "iPhone 16 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=45", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=45" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 4299.99 },
    { name: "iPhone 16 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=46", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=46" }], details: "seminovo|128GB|Bateria boa", category: "seminovos", price: 5399.99 },
    { name: "iPhone 16 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=48", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=48" }], details: "seminovo|256GB|Bateria boa", category: "seminovos", price: 6599.99 },
    { name: "iPhone 13 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=23", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=23" }], details: "novo|lacrado|128GB|Garantia 1 ano Apple", category: "iphones_novos", price: 3249.99 },
    { name: "iPhone 14 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=31", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=31" }], details: "novo|lacrado|128GB|Garantia 1 ano Apple", category: "iphones_novos", price: 3699.99 },
    { name: "iPhone 15 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=40", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=40" }], details: "novo|lacrado|128GB|Garantia 1 ano Apple", category: "iphones_novos", price: 4099.99 },
    { name: "iPhone 16 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=45", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=45" }], details: "novo|lacrado|128GB|Garantia 1 ano Apple", category: "iphones_novos", price: 4899.99 },
    { name: "iPhone 16 Pro 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=46", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=46" }], details: "novo|lacrado|128GB|Garantia 1 ano Apple", category: "iphones_novos", price: 6299.99 },
    { name: "iPhone 16 Pro 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=47", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=47" }], details: "novo|lacrado|256GB|Garantia 1 ano Apple", category: "iphones_novos", price: 6799.99 },
    { name: "iPhone 16 Pro Max 256GB", image: "https://ganhocerto99.com/get-imagem.php?id=48", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=48" }], details: "novo|lacrado|256GB|Garantia 1 ano Apple", category: "iphones_novos", price: 7299.99 },
    { name: "iPhone 17 256GB", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-2-Nnb6dhxiHN9ZQMH8.png", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-2-Nnb6dhxiHN9ZQMH8.png" }], details: "novo|lacrado|256GB|Garantia 1 ano Apple", category: "iphones_novos", price: 6299.99 },
    { name: "iPhone 17 Air 256GB", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/317453_0_js9hgorfqe-WUVDO92hYXNyXFbg.webp", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/317453_0_js9hgorfqe-WUVDO92hYXNyXFbg.webp" }], details: "novo|lacrado|256GB|Preço a consultar", category: "iphones_novos", price: 0.00 },
    { name: "iPhone 17 Pro 256GB", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-pro-max-laranja-cosmico-juVtKK3To8n3TPRS.png", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-pro-max-laranja-cosmico-juVtKK3To8n3TPRS.png" }], details: "novo|lacrado|256GB|Garantia 1 ano Apple", category: "iphones_novos", price: 8999.99 },
    { name: "iPhone 17 Pro Max 256GB", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-pro-max-laranja-cosmico-juVtKK3To8n3TPRS.png", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/iphone-17-pro-max-laranja-cosmico-juVtKK3To8n3TPRS.png" }], details: "novo|lacrado|256GB|Garantia 1 ano Apple", category: "iphones_novos", price: 9599.99 },
    { name: "INFINIX Smart 10 128GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=5", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=5" }], details: "novo|128GB/8GB", category: "smartphones", price: 749.99 },
    { name: "INFINIX HOT 50i 256GB/9GB", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/infinix-hot-50i-2-LL4WVKBnWw7xEMbp.png", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/infinix-hot-50i-2-LL4WVKBnWw7xEMbp.png" }], details: "novo|256GB/9GB", category: "smartphones", price: 899.99 },
    { name: "REALME Note 60X 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=74", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=74" }], details: "novo|128GB/4GB", category: "smartphones", price: 749.99 },
    { name: "Redmi A3 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=81", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=81" }], details: "novo|128GB/4GB", category: "smartphones", price: 799.99 },
    { name: "POCO C71 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=63", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=63" }], details: "novo|128GB/4GB", category: "smartphones", price: 799.99 },
    { name: "Redmi A5 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=83", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=83" }], details: "novo|128GB/4GB", category: "smartphones", price: 799.99 },
    { name: "Redmi 14C 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=77", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=77" }], details: "novo|128GB/4GB", category: "smartphones", price: 849.99 },
    { name: "REALME Note 60 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=73", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=73" }], details: "novo|128GB/4GB", category: "smartphones", price: 849.99 },
    { name: "POCO C65 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=61", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=61" }], details: "novo|128GB/4GB", category: "smartphones", price: 899.99 },
    { name: "POCO C75 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=64", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=64" }], details: "novo|256GB/8GB", category: "smartphones", price: 999.99 },
    { name: "REDMI A5 64GB/3GB", image: "https://ganhocerto99.com/get-imagem.php?id=82", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=82" }], details: "novo|64GB/3GB", category: "smartphones", price: 650.00 },
    { name: "NOTE 70 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=59", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=59" }], details: "novo|256GB/8GB", category: "smartphones", price: 999.99 },
    { name: "POCO C85 128GB/6GB", image: "https://ganhocerto99.com/get-imagem.php?id=65", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=65" }], details: "novo|128GB/6GB", category: "smartphones", price: 999.99 },
    { name: "Redmi 13 128GB/6GB", image: "https://ganhocerto99.com/get-imagem.php?id=75", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=75" }], details: "novo|128GB/6GB", category: "smartphones", price: 999.99 },
    { name: "Redmi 14C 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=78", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=78" }], details: "novo|256GB/8GB", category: "smartphones", price: 999.99 },
    { name: "POCO C65 256GB/6GB", image: "https://ganhocerto99.com/get-imagem.php?id=62", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=62" }], details: "novo|256GB/6GB", category: "smartphones", price: 1099.99 },
    { name: "Redmi 13 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=76", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=76" }], details: "novo|256GB/8GB", category: "smartphones", price: 1099.99 },
    { name: "REDMI 15C 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=80", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=80" }], details: "novo|256GB/8GB", category: "smartphones", price: 1100.00 },
    { name: "REALME C71 256GB/16GB NFC", image: "https://ganhocerto99.com/get-imagem.php?id=70", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=70" }], details: "novo|256GB/16GB|com NFC", category: "smartphones", price: 1100.00 },
    { name: "Redmi Note 14 128GB/6GB", image: "https://ganhocerto99.com/get-imagem.php?id=85", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=85" }], details: "novo|128GB/6GB", category: "smartphones", price: 1100.00 },
    { name: "REDMI 15 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=79", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=79" }], details: "novo|256GB/8GB", category: "smartphones", price: 1150.00 },
    { name: "Redmi Note 14 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=86", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=86" }], details: "novo|256GB/8GB", category: "smartphones", price: 1200.00 },
    { name: "REALME C75X 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=72", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=72" }], details: "novo|256GB/8GB", category: "smartphones", price: 1299.99 },
    { name: "REALME C75 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=71", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=71" }], details: "novo|256GB/8GB", category: "smartphones", price: 1449.99 },
    { name: "Note 14S 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=58", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=58" }], details: "novo|256GB/8GB", category: "smartphones", price: 1499.99 },
    { name: "POCO X7 5G 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=66", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=66" }], details: "novo|256GB/8GB", category: "smartphones", price: 1799.99 },
    { name: "Redmi Note 14 4G 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=84", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=84" }], details: "novo|256GB/8GB", category: "smartphones", price: 1849.99 },
    { name: "POCO X7 5G 512GB/12GB", image: "https://ganhocerto99.com/get-imagem.php?id=67", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=67" }], details: "novo|512GB/12GB", category: "smartphones", price: 1899.99 },
    { name: "Redmi Note 14 Pro 5G 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=87", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=87" }], details: "novo|256GB/8GB", category: "smartphones", price: 1949.99 },
    { name: "POCO X7 Pro 256GB/8GB", image: "https://ganhocerto99.com/get-imagem.php?id=68", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=68" }], details: "novo|256GB/8GB", category: "smartphones", price: 2299.99 },
    { name: "POCO X7 Pro 512GB/12GB", image: "https://ganhocerto99.com/get-imagem.php?id=69", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=69" }], details: "novo|512GB/12GB", category: "smartphones", price: 2449.99 },
    { name: "Capa Silicone - iPhone 8 Plus", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Silicone", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Silicone" }], details: "iPhone 8 Plus", category: "acessorios", price: 20.00 },
    { name: "Capa Silicone - iPhone 16 Pro Max", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Silicone", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Silicone" }], details: "iPhone 16 Pro Max", category: "acessorios", price: 20.00 },
    { name: "Capa MagSafe - iPhone 11", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+MagSafe", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+MagSafe" }], details: "iPhone 11", category: "acessorios", price: 40.00 },
    { name: "Capa MagSafe - iPhone 16 Pro Max", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+MagSafe", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+MagSafe" }], details: "iPhone 16 Pro Max", category: "acessorios", price: 40.00 },
    { name: "Capa Transparente - iPhone 11", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Transparente", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Transparente" }], details: "iPhone 11", category: "acessorios", price: 20.00 },
    { name: "Capa Transparente - iPhone 16 Pro Max", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Transparente", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Capa+Transparente" }], details: "iPhone 16 Pro Max", category: "acessorios", price: 20.00 },
    { name: "Cabo Tipo C", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Cabo+Tipo+C", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Cabo+Tipo+C" }], details: "carregamento e dados", category: "acessorios", price: 40.00 },
    { name: "Base Tipo C", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Base+Tipo+C", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Base+Tipo+C" }], details: "carregador", category: "acessorios", price: 60.00 },
    { name: "Fone de Ouvido P2", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Fone+P2", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Fone+P2" }], details: "3.5mm", category: "acessorios", price: 20.00 },
    { name: "Fone de Ouvido Lightning", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Fone+Lightning", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Fone+Lightning" }], details: "para iPhones", category: "acessorios", price: 50.00 },
    { name: "Cabo USB Foxconn", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Cabo+USB", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Cabo+USB" }], details: "USB para Lightning", category: "acessorios", price: 30.00 },
    { name: "Película de Câmera", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Película", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Película" }], details: "protetora para câmeras", category: "acessorios", price: 30.00 },
    { name: "Película de Celular", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Película", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Película" }], details: "protetora para tela", category: "acessorios", price: 30.00 },
    { name: "Base com entrada Tipo C e USB", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Base+Dupla", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Base+Dupla" }], details: "carregador com múltiplas portas", category: "acessorios", price: 50.00 },
    { name: "Carregador Completo USB para Tipo C", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Carregador", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Carregador" }], details: "kit (base + cabo)", category: "acessorios", price: 80.00 },
    { name: "Carregador Completo USB para Lightning", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Carregador", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Carregador" }], details: "kit (base + cabo)", category: "acessorios", price: 80.00 },
    { name: "JBL Encore", image: "https://ganhocerto99.com/get-imagem.php?id=52", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=52" }], details: "caixa de som", category: "jbl", price: 1449.00 },
    { name: "JBL Boombox 3", image: "https://ganhocerto99.com/get-imagem.php?id=51", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=51" }], details: "caixa de som", category: "jbl", price: 1999.99 },
    { name: "JBL Party Box 120", image: "https://ganhocerto99.com/get-imagem.php?id=53", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=53" }], details: "caixa de som", category: "jbl", price: 2099.00 },
    { name: "JBL Party Box 320", image: "https://ganhocerto99.com/get-imagem.php?id=54", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=54" }], details: "caixa de som", category: "jbl", price: 2899.00 },
    { name: "Boombox 4", image: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/s-XWn5VugWCruuiUuh.webp", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://assets.zyrosite.com/YX4jqgN93jS66PRg/s-XWn5VugWCruuiUuh.webp" }], details: "caixa de som", category: "jbl", price: 3149.99 },
    { name: "JBL Ultimate 1100W", image: "https://ganhocerto99.com/get-imagem.php?id=55", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=55" }], details: "caixa de som", category: "jbl", price: 6399.00 },
    { name: "PlayStation 5", image: "https://ganhocerto99.com/get-imagem.php?id=60", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=60" }], details: "console|com leitor de disco", category: "playstation", price: 3399.00 },
    { name: "MacBook Air M1 256GB / 8GB RAM", image: "https://ganhocerto99.com/get-imagem.php?id=56", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=56" }], details: "Chip M1", category: "macbook", price: 4799.99 },
    { name: "MacBook Air M4 256GB / 16GB RAM", image: "https://ganhocerto99.com/get-imagem.php?id=57", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=57" }], details: "Chip M4", category: "macbook", price: 6699.99 },
    { name: "Apple Watch SE2 40mm", image: "https://ganhocerto99.com/get-imagem.php?id=1", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=1" }], details: "novo", category: "smartwatch", price: 1649.99 },
    { name: "Apple Watch SE2 44mm", image: "https://ganhocerto99.com/get-imagem.php?id=2", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=2" }], details: "novo", category: "smartwatch", price: 1899.99 },
    { name: "Apple Watch Série 10 42mm", image: "https://ganhocerto99.com/get-imagem.php?id=3", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=3" }], details: "novo", category: "smartwatch", price: 2449.99 },
    { name: "Apple Watch Série 10 46mm", image: "https://ganhocerto99.com/get-imagem.php?id=4", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=4" }], details: "novo", category: "smartwatch", price: 2649.99 },
    { name: "iPad 10 64GB", image: "https://ganhocerto99.com/get-imagem.php?id=6", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=6" }], details: "novo", category: "tablets", price: 2249.99 },
    { name: "iPad 11 128GB", image: "https://ganhocerto99.com/get-imagem.php?id=7", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=7" }], details: "novo", category: "tablets", price: 2699.99 },
    { name: "Xiaomi Pad SE Mini 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=88", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=88" }], details: "novo", category: "tablets", price: 949.00 },
    { name: "Xiaomi Redmi Pad 11 128GB/4GB", image: "https://ganhocerto99.com/get-imagem.php?id=89", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://ganhocerto99.com/get-imagem.php?id=89" }], details: "novo", category: "tablets", price: 1299.00 },
    { name: "Reparo em Placa", image: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Serviço", variants: [{ colorName: 'Padrão', colorHex: '#cccccc', imageUrl: "https://placehold.co/400x400/0a0a0a/FFFFFF?text=Serviço" }], details: "Serviço especializado em reparo de placas", category: "assistencia", price: 400.00 },
];

export const seedDatabase = async (storeId: string) => {
    if (!storeId) {
        console.error("seedDatabase: storeId is required");
        return { success: false, message: "ID da loja não fornecido." };
    }

    try {
        const batch = db.batch();
        SEED_PRODUCTS.forEach(productData => {
            const docRef = db.collection('stores').doc(storeId).collection("products").doc(); // Gera um ID automático
            batch.set(docRef, productData);
        });
        await batch.commit();
        console.log("Banco de dados preenchido com sucesso para loja " + storeId);
        return { success: true, message: `${SEED_PRODUCTS.length} produtos foram cadastrados com sucesso!` };
    } catch (error) {
        console.error("Erro ao preencher o banco de dados: ", error);
        return { success: false, message: `Erro ao cadastrar produtos: ${error}` };
    }
};
